### ISSUE TITLE
Asuna - Bug bonusowego dmg z ultimate'a

### ISSUE THREAD

**Issue by odmiex** [tojatos/NKM#2]
Asuna
----------------------------------------------------------------------------------------------------------------
Zbugowany ultimate
Z moich obserwacji wynika, że aktualny bonus jest mnożony razy 2, a nie powinien:
12(base dmg asuny)  + 6(aktualny bonus) - 3(crona def) = 15
A zadaje 21.
Najprawdopodobniej przyczyną jest nakładnie się bonusu z pasywa na aktualny bonus z ultimate’a niezależnie od odległości.

![screenshot 2018-06-04 14 22 04](https://user-images.githubusercontent.com/24724209/40917983-4df0e296-6805-11e8-88fd-95109fa1cce1.png)

**Comment by tojatos** [comment]
Fixed some time ago during system changes
